# Generated by Django 2.1.5 on 2019-01-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('estoque', models.PositiveIntegerField()),
                ('quant_comprada', models.IntegerField()),
            ],
        ),
    ]
