# Generated by Django 2.1.5 on 2019-01-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compra.Item'),
            preserve_default=False,
        ),
    ]
