# Generated by Django 2.1.5 on 2019-01-28 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_remove_item_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compra.Compra'),
            preserve_default=False,
        ),
    ]
